[tool.poetry]
name = "celery-docker"
version = "0.2.0"
description = ""

[tool.poetry.dependencies]
python = "^3.6"
celery = "^5.0.4"
gevent = "^20.9.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
