version: '3.4'
services:
  worker:
    build: .
    image: &img worker
    command: [celery, -A, tasks, worker, --pool=gevent, --concurrency=20, --loglevel=INFO]
    environment: &env
      - CELERY_BROKER_URL=amqp://admin:mypass@172.17.0.1:5672
    depends_on:
      - beat
    restart: 'no'
    volumes:
      - ./app:/app

  beat:
    build: .
    image: *img
    command: [celery, -A, tasks, beat, --loglevel=INFO]
    environment: *env
    restart: 'no'
    volumes:
      - ./app:/app